### ISSUE TITLE
Dark mode issues on macOS

### ISSUE THREAD

**Issue by LoganDark** [wxFormBuilder/wxFormBuilder#625]
Now, I recognize that nobody has gotten wxFormBuilder to build and run on a recent version of macOS in a long time (#525). However, I've managed to get mine to work simply by building wxWidgets from source and using a hack to make wxFormBuilder find the library it wants (https://github.com/wxFormBuilder/wxFormBuilder/issues/525#issuecomment-660439943).

Here's the current state of the UI:
![image](https://user-images.githubusercontent.com/4723091/87859050-3cb95180-c8e7-11ea-83ec-d7935f2610af.png)

There are a few issues right off the bat:
- In the left tree view, selected items turn white when the tree view is not in focus (when it's in focus things look fine)
- AUI panel titles have a bright grey background
- Inactive AUI tab colors are grey and not very visible
- Window titlebars are grey and the title is not visible (in this example, it's set to "Login")
- Background colors in the property inspector are slightly obnoxious

I'm not sure how much of this can be fixed, and I've _also_ been told that none of the main developers have a Mac themselves. However, these are all quite simple tweaks and since C++ is one of my native languages I'd be happy to open a pull request if there's a need for it.

**Comment by LoganDark** [comment]
Note that the tree view thing manifests itself **exactly the same** in really old versions of wxFormBuilder that don't support the dark theme.

![image](https://user-images.githubusercontent.com/4723091/87859304-054ba480-c8e9-11ea-8f29-ccb9d64324b5.png)

It looks like the tree view hasn't been changed at all in this time. A proper fix would also fix the text color on light theme.

**Comment by Kvaz1r** [comment]
I seen recently several changes to AUI dark mode under OSX in wxWidgets repo, for example this one - [https://github.com/wxWidgets/wxWidgets/pull/1955](Fixes for AUI in dark mode under macOS) 
Did you build wxFormBuilder with those changes?

**Comment by LoganDark** [comment]
I downloaded the source from wxWidgets' website, if you want me to try building master I can

**Comment by Kvaz1r** [comment]
Yes, it would be great - maybe some of issue already was fixed and some maybe related to wxWidgets itself.

**Comment by sodevel** [comment]
> There are a few issues right off the bat:
> 
>     * In the left tree view, selected items turn white when the tree view is not in focus (when it's in focus things look fine)
> 
>     * AUI panel titles have a bright grey background
> 
>     * Inactive AUI tab colors are grey and not very visible

These issues should all be wxWidgets issues, i don't think wxFB modifies any of these colors

>     * Window titlebars are grey and the title is not visible (in this example, it's set to "Login")

This is a wxFB issue, these Windows 95 title bars are self drawn
 
>     * Background colors in the property inspector are slightly obnoxious

You can blame me for this, i have chosen these colors because they fit quite good for the Adapta Theme on CentOS 7 i am using.

![2020-03-26_17-21-07_wxFB_Darkmode_Adapta](https://user-images.githubusercontent.com/29261375/87860815-c9442e00-c940-11ea-8bba-f99a0b83cc74.png)

> I'm not sure how much of this can be fixed, and I've _also_ been told that none of the main developers have a Mac themselves. However, these are all quite simple tweaks and since C++ is one of my native languages I'd be happy to open a pull request if there's a need for it.

I don't want to demotivate you but it is actually not so easy. Like you already mentioned the current color scheme doesn't look well on your Mac, it also doesn't look well on my CentOS 7 when using the BlackMATE theme and from the posted link above changing the AUI colors also is not trivial to make it work accross all environments.

**Comment by LoganDark** [comment]
> These issues should all be wxWidgets issues, i don't think wxFB modifies any of these colors

I think the linked PR from earlier should solve those issues. Right now I'm waiting for a build of wxWidgets `master` to complete so I can link wxFormBuilder against that one.

![image](https://user-images.githubusercontent.com/4723091/87861710-b52b0d00-c8fd-11ea-84ea-3e50c08aff59.png)

> This is a wxFB issue, these Windows 95 title bars are self drawn

Yes, I know that. Honestly, I could PR to draw more macOS-like title bars on macOS. Those would support light them and dark theme. Alternatively I could just change the colors a bit to be sensitive to dark themes.

> You can blame me for this, i have chosen these colors because they fit quite good for the Adapta Theme on CentOS 7 i am using.

Nice :D

> I don't want to demotivate you but it is actually not so easy. Like you already mentioned the current color scheme doesn't look well on your Mac, it also doesn't look well on my CentOS 7 when using the BlackMATE theme and from the posted link above changing the AUI colors also is not trivial to make it work accross all environments.

Rather than picking arbitrary colors, wxFB _could_ tint the existing background color. I think that would work for light themes and dark themes, but I'll need to test it out beforehand and see how it works.

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/87862068-db9e7780-c900-11ea-8e17-ae930d985a46.png)

Issues:
- selected item still white in the tree view
- panel titles still bright grey
- tab colors still grey
- window titlebar and property inspector are the same (but that's not wxWidgets' fault)

basically, nothing changed. I can't find even 1 difference between my screenshot from before and this one. (except for the fact the project is called Login now)

**Comment by LoganDark** [comment]
Oh wait, I found one! This button has a grey background.

![image](https://user-images.githubusercontent.com/4723091/87862144-caa23600-c901-11ea-8c44-b41eea0fdec8.png)

I can't believe I was so blind before!

**Comment by sodevel** [comment]
It has a grey background because it is selected, this was already working before as can be seen in your first screenshot at that one alignment button. I have used https://github.com/wxWidgets/wxWidgets/commit/6a2005945aafcd9e3e81661f815a7a2064a96cc7 and can see some small but nice changes in my environment:

![Bildschirmfoto zu 2020-07-20 19-16-42](https://user-images.githubusercontent.com/29261375/87967327-f0c10500-cabe-11ea-8494-14a5411558dc.png)

Is there any chance your MacOS is using a HiDPI screen, because this wrong spacing in the toolbar and the height of the AUI title bars look like scaling issues, if wxFB doesn't set any of these values itself (didn't check that yet) this should be reported to wxWidgets.

**Comment by LoganDark** [comment]
> It has a grey background because it is selected, this was already working before as can be seen in your first screenshot at that one alignment button

that's the joke, they fixed a bug because the first screenshot did not have that grey background

> Is there any chance your MacOS is using a HiDPI screen

Yes

**Comment by redtide** [comment]
Still an issue on Linux as well (Archlinux LXQt)
![immagine](https://user-images.githubusercontent.com/1171962/116870104-2da35600-ac12-11eb-871b-07c651048f8f.png)

**Comment by sodevel** [comment]
As i said before, some skins use different colors which makes it quite difficult to please them all by using hardcoded values with limited detection logic. Not sure what you want to display with that screenshot, but if it's the tab and section labels color, this looks quite familiar to me. Older wxWidgets versions produced that output for me, recent master snapshots fixed that for me :wink:

**Comment by redtide** [comment]
There are 2 solutions, one is to force predefined colors (IDK if possible, need to check wxWidgets AUI code). The second would be to have GTK theme detection in wx, so in this case if it's already fixed as you said all the better, otherwise the only alternative would be to send a patch upstream. The screenshot shows that both unselected AUI notebook tabs and wxPropertyGrid group titles has a wrong color.

**Comment by redtide** [comment]
see also #374

**Comment by redtide** [comment]
It seems it was a wx issue that was fixed in this (3.1.4?) [commit](https://github.com/wxWidgets/wxWidgets/commit/aae96a430609bacfa546f0a872cf1a94e8a0b073), I somewhat backported it in `auitabbar.h` and seems to work but not enough tested yet.
I'll try to see if I can also fix the property grid category titles and send a draft PR to be tested.
![immagine](https://user-images.githubusercontent.com/1171962/117222838-b4bc1e00-ae0c-11eb-8219-05c68a3f624f.png)

**Comment by sodevel** [comment]
I wouldn't waste time on fixing issues that fix themself by simply upgrading wxWidgets. There are more serious issues with wxWidgets 3.0 than these visual defects that make wxFB much more unusable. Especially on MacOS this upgrade is easy because you have to build wxWidgets yourself anyway, it's only Linux that does not ship wxWidgets 3.1 as packages which makes it a bit more difficult there, but this can be worked around with Flatpak / Snap.

**Comment by redtide** [comment]
Well, someone asked me for this and I did, if you don't care that is your own opinion. I give up here.

**Comment by LoganDark** [comment]
> I wouldn't waste time on fixing issues that fix themself by simply upgrading wxWidgets. There are more serious issues with wxWidgets 3.0 than these visual defects that make wxFB much more unusable. Especially on MacOS this upgrade is easy because you have to build wxWidgets yourself anyway, it's only Linux that does not ship wxWidgets 3.1 as packages which makes it a bit more difficult there, but this can be worked around with Flatpak / Snap.

I believe that when I made this issue the latest wxWidgets version was 3.1.3 and it did still have these issues. There was no newer version to upgrade to. Although now I'm sure the latest version has now ironed out the kinks with dark mode and it should work just fine.

**Comment by redtide** [comment]
@LoganDark: the point is that in a system odd development versions (2.9, 3.1 and so on) are not installed, so there is no way to update until 3.2 will come out or someone should build wx himself, which is not something a regular user does. That was an answer that looks like from someone which won't take responsibilities of fixing bugs, not even when someone has fixed them and proposed to make a PR. Now unsubscribing, this was one reasons I made my own fork.

**Comment by LoganDark** [comment]
> That was an answer that looks like from someone which won't take responsibilities of fixing bugs, not even when someone has fixed them and proposed to make a PR

Agreed. Good luck with your fork :)
